spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/Users/handaxingyuner/code/gitCode/graduation/src/main/resources/h2/graduation;AUTO_SERVER=TRUE
    username: sa
    password: sa