spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://35.241.68.51:3306/graduation
    username: root
    password: f877j/fC^-7b

  h2:
    console:
      enabled: true
logging:
  config: classpath:log4j2.xml
  level:
    root: info